# Generated by Django 3.1.13 on 2021-07-19 06:47


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('H1stModel', '0006_kerasmodel_tfmodel_torchmodel')
    ]

    operations = [
        migrations.CreateModel(
            name='KerasImageNetClassifier',

            fields=[
                ('model_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='H1stModel.model')),

                ('name',
                 models.CharField(
                    choices=[
                        ('DenseNet121', 'DenseNet121'),
                        ('DenseNet169', 'DenseNet169'),
                        ('DenseNet201', 'DenseNet201'),

                        ('EfficientNetB0', 'EfficientNetB0'),
                        ('EfficientNetB1', 'EfficientNetB1'),
                        ('EfficientNetB2', 'EfficientNetB2'),
                        ('EfficientNetB3', 'EfficientNetB3'),
                        ('EfficientNetB4', 'EfficientNetB4'),
                        ('EfficientNetB5', 'EfficientNetB5'),
                        ('EfficientNetB6', 'EfficientNetB6'),
                        ('EfficientNetB7', 'EfficientNetB7'),

                        ('InceptionResNetV2', 'InceptionResNetV2'),
                        ('InceptionV3', 'InceptionV3'),

                        ('MobileNet', 'MobileNet'),
                        ('MobileNetV2', 'MobileNetV2'),
                        ('MobileNetV3Large', 'MobileNetV3Large'),
                        ('MobileNetV3Small', 'MobileNetV3Small'),

                        ('NASNetLarge', 'NASNetLarge'),
                        ('NASNetMobile', 'NASNetMobile'),

                        ('ResNet50', 'ResNet50'),
                        ('ResNet101', 'ResNet101'),
                        ('ResNet152', 'ResNet152'),

                        ('ResNet50V2', 'ResNet50V2'),
                        ('ResNet101V2', 'ResNet101V2'),
                        ('ResNet152V2', 'ResNet152V2'),

                        ('VGG16', 'VGG16'),
                        ('VGG19', 'VGG19'),

                        ('Xception', 'Xception')
                    ],
                    db_index=True,
                    default=None,
                    help_text='Keras ImageNet Classifier Name',
                    max_length=255,
                    unique=True,
                    verbose_name='Keras ImageNet Classifier Name'))
            ],

            options={
                'verbose_name': 'Keras ImageNet Classifier',
                'verbose_name_plural': 'Keras ImageNet Classifiers',
            },

            bases=('H1stModel.model',)
        )
    ]
