# Generated by Django 3.1.13 on 2021-07-20 00:43


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('H1stModel', '0007_optional_unique_name')
    ]

    operations = [
        migrations.CreateModel(
            name='KerasImageNetClassifier',
            fields=[
                ('model_ptr',
                 models.OneToOneField(
                    auto_created=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    parent_link=True,
                    primary_key=True,
                    serialize=False,
                    to='H1stModel.model'))
            ],

            options={'abstract': False,
                     'base_manager_name': 'objects'},

            bases=('H1stModel.model',))
    ]
